name: sql-formatter-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - notebook
  - jupyter_contrib_nbextensions
  - pre-commit
  - pip
  - pip:
      - nbdev==1.1.5
      - twine
