name: sql-formatter-dev
channels:
  - defaults
  - conda-forge
  - fastai
  - pablormira
dependencies:
  - python=3.7
  - notebook
  - jupyter_contrib_nbextensions
  - pip
  - nbdev=1.1.5
  - twine
  - easyrelease
