# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MAIN_STATEMENTS": "00_core.ipynb",
         "clean_query": "00_core.ipynb",
         "preformat_statements": "00_core.ipynb",
         "lowercase_query": "00_core.ipynb",
         "add_whitespaces_query": "00_core.ipynb",
         "format_partition_by": "00_core.ipynb",
         "remove_wrong_end_comma": "00_core.ipynb",
         "format_case_when": "00_core.ipynb",
         "format_select": "00_core.ipynb",
         "format_from": "00_core.ipynb",
         "format_join": "00_core.ipynb",
         "format_on": "00_core.ipynb",
         "format_where": "00_core.ipynb",
         "format_statement_line": "00_core.ipynb",
         "format_statements": "00_core.ipynb",
         "format_multiline_comments": "00_core.ipynb",
         "add_semicolon": "00_core.ipynb",
         "format_simple_sql": "00_core.ipynb",
         "format_sql": "00_core.ipynb",
         "format_sql_commands": "01_format_file.ipynb",
         "format_sql_file": "01_format_file.ipynb",
         "format_sql_files": "01_format_file.ipynb",
         "assert_and_print": "02_utils.ipynb",
         "compress_dicts": "02_utils.ipynb",
         "remove_whitespaces_newline": "02_utils.ipynb",
         "remove_whitespaces_comments": "02_utils.ipynb",
         "remove_redundant_whitespaces": "02_utils.ipynb",
         "remove_whitespaces_parenthesis": "02_utils.ipynb",
         "add_whitespaces_between_symbols": "02_utils.ipynb",
         "mark_ci_comments": "02_utils.ipynb",
         "mark_comments": "02_utils.ipynb",
         "split_query": "02_utils.ipynb",
         "split_apply_concat": "02_utils.ipynb",
         "split_comment_quote": "02_utils.ipynb",
         "split_comment": "02_utils.ipynb",
         "identify_in_sql": "02_utils.ipynb",
         "split_by_semicolon": "02_utils.ipynb",
         "replace_newline_chars": "02_utils.ipynb",
         "identify_end_of_fields": "02_utils.ipynb",
         "add_newline_indentation": "02_utils.ipynb",
         "extract_outer_subquery": "02_utils.ipynb",
         "format_subquery": "02_utils.ipynb",
         "check_sql_query": "02_utils.ipynb",
         "check_skip_marker": "02_utils.ipynb",
         "identify_create_table_view": "02_utils.ipynb",
         "count_lines": "02_utils.ipynb",
         "find_line_number": "02_utils.ipynb",
         "jaccard_distance": "02_utils.ipynb",
         "assign_comment": "02_utils.ipynb",
         "validate_semicolon": "03_validation.ipynb",
         "validate_balanced_parenthesis": "03_validation.ipynb",
         "validate_case_when": "03_validation.ipynb"}

modules = ["core.py",
           "format_file.py",
           "utils.py",
           "validation.py"]

doc_url = "https://PabloRMira.github.io/sql_formatter/"

git_url = "https://github.com/PabloRMira/sql_formatter/tree/master/"

def custom_doc_links(name): return None
