# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MAIN_STATEMENTS": "00_core.ipynb",
         "capitalize_statements": "00_core.ipynb",
         "remove_newlines": "00_core.ipynb",
         "breakline_statement": "00_core.ipynb",
         "OPERATORS": "00_core.ipynb",
         "lower_operators": "00_core.ipynb",
         "validate_select": "00_core.ipynb",
         "format_select": "00_core.ipynb",
         "format_from": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://PabloRMira.github.io/sql_formatter/"

git_url = "https://github.com/PabloRMira/sql_formatter/tree/master/"

def custom_doc_links(name): return None
