# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"assert_and_print": "00_core.ipynb",
         "MAIN_STATEMENTS": "00_core.ipynb",
         "CAPITAL_STATEMENTS": "00_core.ipynb",
         "capitalize_statements": "00_core.ipynb",
         "remove_newlines_mspaces": "00_core.ipynb",
         "breakline_statement": "00_core.ipynb",
         "format_select": "00_core.ipynb",
         "format_from": "00_core.ipynb",
         "format_join": "00_core.ipynb",
         "add_whitespaces_between_symbols": "00_core.ipynb",
         "format_on": "00_core.ipynb",
         "format_where": "00_core.ipynb",
         "format_statement_line": "00_core.ipynb",
         "format_statements": "00_core.ipynb",
         "add_ending_semicolon": "00_core.ipynb",
         "format_simple_sql": "00_core.ipynb",
         "extract_outer_subquery": "00_core.ipynb",
         "format_subquery": "00_core.ipynb",
         "format_sql": "00_core.ipynb",
         "check_sql_query": "01_sql_file_formatter.ipynb",
         "format_sql_commands": "01_sql_file_formatter.ipynb",
         "format_sql_file": "01_sql_file_formatter.ipynb"}

modules = ["core.py",
           "sql_file_formatter.py"]

doc_url = "https://PabloRMira.github.io/sql_formatter/"

git_url = "https://github.com/PabloRMira/sql_formatter/tree/master/"

def custom_doc_links(name): return None
