# AUTOGENERATED! DO NOT EDIT! File to edit: 01_sql_file_formatter.ipynb (unless otherwise specified).

__all__ = ['check_sql_query', 'format_sql_commands', 'format_sql_file']

# Cell
import re
import os
from .core import format_sql, assert_and_print

# Cell
def check_sql_query(s):
    "Checks whether `s` is a SQL query"
    return bool(re.match(pattern=r"^\n*(?:select|create)", string=s, flags=re.I))

# Cell
def format_sql_commands(s):
    "Format SQL commands in `s`"
    split_s = s.split(";")  # split by semicolon
    formatted_split_s = [
        "\n\n" + format_sql(sp, add_semicolon=False)
        if check_sql_query(sp)
        else sp
        for sp in split_s
    ]
    formatted_s = ";".join(formatted_split_s)
    return formatted_s

# Cell
def format_sql_file(f):
    "Format SQL file `f`"
    with open(f, "r") as file:
        sql_commands = file.read()
    formatted_sql_commands = format_sql_commands(sql_commands)
    return formatted_sql_commands